spring:
  profiles:
    active: develop
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?autoReconnect=true&useUnicode=true&createDatabaseIfNotExist=true&characterEncoding=utf8&useSSL=true&serverTimezone=UTC
    username: root
    password: 123
    minIdle: 1
    maxActive: 2
    initialSize: 1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
mybatis:
  configLocations: classpath:mapper/mybatis/mybatis-config.xml
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: com.example.demo.domain
server:
  port: 8081
  servlet:
    context-path: /boot